### PR TITLE
Merge upstream/humble into feature branch

### PR DESCRIPTION
**Pull request by sjahr**
Merge upstream/humble into out feature branch to get https://github.com/PickNikRobotics/gz_ros2_control/commit/f724da5d37d3a9f88ee38d2aea05899679c3c448 and avoid segfault

### CODE REVIEW

**Review by MikeWrock — APPROVED** [review]
Was it the `get_parameter_or` causing the segfault or something in the version bump fixes the issue?

**Comment by sjahr** [comment]
> Was it the `get_parameter_or` causing the segfault or something in the version bump fixes the issue?

get_parameter_or without the try catch protection

**Comment by sjahr** [comment]
> Was it the `get_parameter_or` causing the segfault or something in the version bump fixes the issue?

get_parameter_or without the try catch protection

**Comment by sjahr** [comment]
> Was it the `get_parameter_or` causing the segfault or something in the version bump fixes the issue?

get_parameter_or without the try catch protection

**Pull request merged**
